apiVersion: v1
kind: Service
metadata:
  labels:
    app: opentelemetry-collector
  name: opentelemetry-collector
  namespace: myproject
spec:
  clusterIP: 172.30.43.97
  ports:
    - name: 4317-tcp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 1443
    - name: 55678-tcp
      port: 55678
      protocol: TCP
      targetPort: 55678
    - name: 55679-tcp
      port: 55679
      protocol: TCP
      targetPort: 55679
  selector:
    deploymentconfig: opentelemetry-collector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
