apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: myproject
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:  
      prometheus:
        endpoint: '0.0.0.0:1443'
        namespace: my-project
        send_timestamps: true
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true
      logging:
        loglevel: debug
        sampling_initial: 5
        sampling_thereafter: 200

    processors:
      batch:

    extensions:
      health_check:

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]

