name: "Build and Release"
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    permissions:
      packages: write
      contents: read
      
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: "alexgenon"
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Run build with Gradle Wrapper
        run: ./gradlew publish
