name: "Build"
on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/*'
      - 'core/*'
      - 'frontend/*'
      - '.github/workflows/integration_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
